config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :employees


  #public pages routes
  get 'about_us' => 'pages#about_us'
  get 'contact_us' => 'pages#contact_us'
  get 'privacy_policy' => 'pages#privacy_policy'
  get 'terms_and_conditions' => 'pages#terms_and_conditions'
  #get 'welcome/index'
  # get '/home' => 'home#index'

  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
# app/models/employee.rb
class Employee < ApplicationRecord
    validates :name, presence: true, length: { maximum: 50 }
    validates :age, presence: true, numericality: { only_integer: true, greater_than: 0 }
    validates :department, length: { maximum: 50 }
    validates :position, length: { maximum: 50 }
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_path, notice: 'Employee was successfully created.'
    else
      render :new
    end
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :age, :department, :position)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def privacy_policy
  end

  def terms_and_conditions
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @title_text = 'Hello World'
        @subtitle_text = 'I am learning rails!'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employees/index.html.erb
<h1>Employees</h1>
<%= flash[:notice] %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Department</th>
      <th>Position</th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.age %></td>
        <td><%= employee.department %></td>
        <td><%= employee.position %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1> Create new Employees</h1>

<%= form_with model: @employee do |form| %>
    <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% @employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
  
    <div class="form-group">
      <%= form.label :age %>
      <%= form.number_field :age, class: "form-control" %>
    </div>
  
    <div class="form-group">
      <%= form.label :department %>
      <%= form.text_field :department, class: "form-control" %>
    </div>
  
    <div class="form-group">
      <%= form.label :position %>
      <%= form.text_field :position, class: "form-control" %>
    </div>
  
    <%= form.submit "Create Employee", class: "btn btn-primary" %>
  <% end %>
  

<%= link_to 'ALL Employee', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentMgmt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pages/about_us.html.erb
<h1>Pages#about_us</h1>
<p>Find me in app/views/pages/about_us.html.erb</p>

app/views/pages/contact_us.html.erb
<h1>Pages#contact_us</h1>
<p>Find me in app/views/pages/contact_us.html.erb</p>

app/views/pages/privacy_policy.html.erb
<h1>Pages#privacy_policy</h1>
<p>Find me in app/views/pages/privacy_policy.html.erb</p>

app/views/pages/terms_and_conditions.html.erb
<h1>Pages#terms_and_conditions</h1>
<p>Find me in app/views/pages/terms_and_conditions.html.erb</p>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/welcome/index.html.erb
<h1> <%= @title_text %> </h1>

<p> <%= @subtitle_text %> </p>


<%= link_to 'About Us', controller: :pages, action: :about_us %>
<!-- <%= link_to 'About Us', about_us_path %> -->
<%= link_to 'About Us', '/about_us' %>
<%= link_to nil, about_us_path %>